/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TemplateMatchingRouteImport } from './routes/template-matching'
import { Route as ViolaJonesRouteImport } from './routes/viola-jones'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TemplateMatchingRoute = TemplateMatchingRouteImport.update({
  id: '/template-matching',
  path: '/template-matching',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolaJonesRoute = ViolaJonesRouteImport.update({
  id: '/viola-jones',
  path: '/viola-jones',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/template-matching': typeof TemplateMatchingRoute
  '/viola-jones': typeof ViolaJonesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/template-matching': typeof TemplateMatchingRoute
  '/viola-jones': typeof ViolaJonesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/template-matching': typeof TemplateMatchingRoute
  '/viola-jones': typeof ViolaJonesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/template-matching' | '/viola-jones'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/template-matching' | '/viola-jones'
  id: '__root__' | '/' | '/template-matching' | '/viola-jones'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TemplateMatchingRoute: typeof TemplateMatchingRoute
  ViolaJonesRoute: typeof ViolaJonesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/template-matching': {
      id: '/template-matching'
      path: '/template-matching'
      fullPath: '/template-matching'
      preLoaderRoute: typeof TemplateMatchingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viola-jones': {
      id: '/viola-jones'
      path: '/viola-jones'
      fullPath: '/viola-jones'
      preLoaderRoute: typeof ViolaJonesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TemplateMatchingRoute: TemplateMatchingRoute,
  ViolaJonesRoute: ViolaJonesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
